[BACKLOG-35000] Adding com.hitachivantara.security.web packages to custom.properties
pentaho/pentaho-karaf-assembly pull request #651
Opened 2021-04-19 15:02 UTC by dcleao

Is this the most central place to add these dependencies to Karaf?
Besides the EE version, is there any other Karaf assembly that security-web should be added to?

Please, review:
@graimundo
/cc @bennychow if you want to review, be my guest!
/cc @jcarneirohv

Depends on pentaho/security-web#4.

2021-06-02 15:48 UTC, graimundo requested changes

2021-06-02 15:48 UTC, graimundo commented on assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
> + com.hitachivantara.security.web.*;version="${hv-security-web.version}"
Changes are only for pentaho server, remove the package export from here as this affects other assemblies such as PDI.

2021-06-02 15:48 UTC, graimundo commented on assemblies/server/src/main/resources-filtered/etc/custom.properties
> + com.hitachivantara.security.web.*;version="${hv-security-web.version}"
As per our conversation in slack, check if its possible to only export the API packages.

2021-06-07 15:50 UTC, dcleao commented
Rebased into master.

2021-06-07 15:56 UTC, dcleao commented
Addressed code review comments.

2021-06-08 12:07 UTC, dcleao commented
Had to revert the export "api.*" only change. The reason being the `pentaho / data-refinery-pdi-plugin` OSGi bundle, which is installed in the Pentaho server. This bundle uses the CSRF JAXRS-v1 client, in the `ModelServerPublish` action, which is only really used when this bundle is installed in PDI. Nonetheless, OSGi bootstrap would fail if the `com.hitachivantara.security.web / csrf-token-service-client-java-jax-rs-v1` **bundle** wouldn't be available.

Making both the `api` and `impl` packages be exported from the root bundle is an easy, quick fix to this problem.
We can discuss later whether we should:
1. Keep this solution
2. Change the data refinery plugin to include the impl dependency (Maven `<scope>compile</scopoe>`).
3. Create a Karaf feature with the impl bundles of the Security Web library.

2021-06-14 16:35 UTC, dcleao commented
Reverted the previous revert, choosing to add the implementation dependency to the PDI data refinery feature instead.

2021-06-17 10:10 UTC, graimundo approved these changes

2021-06-17 14:27 UTC, merged